version: "3"

services:
  psql:
    build: ./docker/db
    container_name: shortener-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
      - POSTGRES_DB=shortener
    volumes:
      - db_psql_data:/var/lib/postgresql/data
    networks:
      - shortener-api

networks:
  shortener-api:
    driver: bridge

volumes:
  db_psql_data:
    driver: local
